# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

heldoutprob_importance <- function(contact, ncategories_contacts, w, Phi, Kx, Ky, kernelx, kernely, q, w_indices, zhome, zoptions, nzoptions, optiondiffsx, optiondiffsy, nsim_per = 10L, status = 1L) {
    .Call('_cindRella_heldoutprob_importance', PACKAGE = 'cindRella', contact, ncategories_contacts, w, Phi, Kx, Ky, kernelx, kernely, q, w_indices, zhome, zoptions, nzoptions, optiondiffsx, optiondiffsy, nsim_per, status)
}

heldoutprob_importance_now <- function(contact, ncategories_contacts, Phi, Kx, Ky, kernelx, kernely, q, zhome, zoptions, nzoptions, optiondiffsx, optiondiffsy, nsim_per = 10L, status = 1L) {
    .Call('_cindRella_heldoutprob_importance_now', PACKAGE = 'cindRella', contact, ncategories_contacts, Phi, Kx, Ky, kernelx, kernely, q, zhome, zoptions, nzoptions, optiondiffsx, optiondiffsy, nsim_per, status)
}

heldoutprob_importance_noZ <- function(contact, ncategories_contacts, w, Phi, q, w_indices, zhome, nsim_per = 10L, status = 1L) {
    .Call('_cindRella_heldoutprob_importance_noZ', PACKAGE = 'cindRella', contact, ncategories_contacts, w, Phi, q, w_indices, zhome, nsim_per, status)
}

heldoutprob_importance_noepsilon <- function(contact, ncategories_contacts, w, Phi, Kx, Ky, kernelx, kernely, w_indices, zhome, zoptions, nzoptions, optiondiffsx, optiondiffsy, status = 1L) {
    .Call('_cindRella_heldoutprob_importance_noepsilon', PACKAGE = 'cindRella', contact, ncategories_contacts, w, Phi, Kx, Ky, kernelx, kernely, w_indices, zhome, zoptions, nzoptions, optiondiffsx, optiondiffsy, status)
}

heldoutprob_importance_noepsilonnoZ <- function(contact, ncategories_contacts, w, Phi, w_indices, zhome, status = 1L) {
    .Call('_cindRella_heldoutprob_importance_noepsilonnoZ', PACKAGE = 'cindRella', contact, ncategories_contacts, w, Phi, w_indices, zhome, status)
}

heldoutprob_importance_noPhi <- function(contact, w, Kx, Ky, kernelx, kernely, q, w_indices, zhome, zoptions, nzoptions, optiondiffsx, optiondiffsy, nsim_per = 10L, status = 1L) {
    .Call('_cindRella_heldoutprob_importance_noPhi', PACKAGE = 'cindRella', contact, w, Kx, Ky, kernelx, kernely, q, w_indices, zhome, zoptions, nzoptions, optiondiffsx, optiondiffsy, nsim_per, status)
}

mcmc_inference <- function(shoenums, contacts, ncategories_contacts, nshoes, z_init, w_init, w_indices, zhome, zoptions, nzoptions, optiondiffsx, optiondiffsy, phi_init, Ax, Ay, Kx, Ky, px_init, py_init, sigma, u_init, q_init, qa, qb, rhox_init, rhoy_init, nsim = 10L, print_output = 1L, nburn = 0L, nthin = 1L, status = 1L) {
    .Call('_cindRella_mcmc_inference', PACKAGE = 'cindRella', shoenums, contacts, ncategories_contacts, nshoes, z_init, w_init, w_indices, zhome, zoptions, nzoptions, optiondiffsx, optiondiffsy, phi_init, Ax, Ay, Kx, Ky, px_init, py_init, sigma, u_init, q_init, qa, qb, rhox_init, rhoy_init, nsim, print_output, nburn, nthin, status)
}

mcmc_inference_noZ <- function(shoenums, contacts, ncategories_contacts, nshoes, w_init, w_indices, zhome, phi_init, Ax, Ay, u_init, q_init, qa, qb, rhox_init, rhoy_init, nsim = 10L, print_output = 1L, nburn = 0L, nthin = 1L, status = 1L) {
    .Call('_cindRella_mcmc_inference_noZ', PACKAGE = 'cindRella', shoenums, contacts, ncategories_contacts, nshoes, w_init, w_indices, zhome, phi_init, Ax, Ay, u_init, q_init, qa, qb, rhox_init, rhoy_init, nsim, print_output, nburn, nthin, status)
}

mcmc_inference_now <- function(shoenums, contacts, ncategories_contacts, nshoes, z_init, zhome, zoptions, nzoptions, optiondiffsx, optiondiffsy, phi_init, Ax, Ay, Kx, Ky, px_init, py_init, sigma, u_init, q_init, qa, qb, nsim = 10L, print_output = 1L, nburn = 0L, nthin = 1L, status = 1L) {
    .Call('_cindRella_mcmc_inference_now', PACKAGE = 'cindRella', shoenums, contacts, ncategories_contacts, nshoes, z_init, zhome, zoptions, nzoptions, optiondiffsx, optiondiffsy, phi_init, Ax, Ay, Kx, Ky, px_init, py_init, sigma, u_init, q_init, qa, qb, nsim, print_output, nburn, nthin, status)
}

mcmc_inference_noepsilon <- function(shoenums, contacts, ncategories_contacts, nshoes, z_init, w_init, w_indices, zhome, zoptions, nzoptions, optiondiffsx, optiondiffsy, phi_init, Ax, Ay, Kx, Ky, px_init, py_init, sigma, rhox_init, rhoy_init, nsim = 10L, print_output = 1L, nburn = 0L, nthin = 1L, status = 1L) {
    .Call('_cindRella_mcmc_inference_noepsilon', PACKAGE = 'cindRella', shoenums, contacts, ncategories_contacts, nshoes, z_init, w_init, w_indices, zhome, zoptions, nzoptions, optiondiffsx, optiondiffsy, phi_init, Ax, Ay, Kx, Ky, px_init, py_init, sigma, rhox_init, rhoy_init, nsim, print_output, nburn, nthin, status)
}

mcmc_inference_noepsilonnoZ <- function(shoenums, contacts, ncategories_contacts, nshoes, w_init, w_indices, zhome, phi_init, Ax, Ay, rhox_init, rhoy_init, nsim = 10L, print_output = 1L, nburn = 0L, nthin = 1L, status = 1L) {
    .Call('_cindRella_mcmc_inference_noepsilonnoZ', PACKAGE = 'cindRella', shoenums, contacts, ncategories_contacts, nshoes, w_init, w_indices, zhome, phi_init, Ax, Ay, rhox_init, rhoy_init, nsim, print_output, nburn, nthin, status)
}

mcmc_inference_noPhi <- function(shoenums, nshoes, z_init, w_init, w_indices, zhome, zoptions, nzoptions, optiondiffsx, optiondiffsy, Ax, Ay, Kx, Ky, px_init, py_init, sigma, u_init, q_init, qa, qb, rhox_init, rhoy_init, nsim = 10L, print_output = 1L, nburn = 0L, nthin = 1L, status = 1L) {
    .Call('_cindRella_mcmc_inference_noPhi', PACKAGE = 'cindRella', shoenums, nshoes, z_init, w_init, w_indices, zhome, zoptions, nzoptions, optiondiffsx, optiondiffsy, Ax, Ay, Kx, Ky, px_init, py_init, sigma, u_init, q_init, qa, qb, rhox_init, rhoy_init, nsim, print_output, nburn, nthin, status)
}

plot_posterior <- function(contact, w, Phi, kernelx, kernely, q, w_indices, zoptions, nzoptions, optiondiffsx, optiondiffsy) {
    .Call('_cindRella_plot_posterior', PACKAGE = 'cindRella', contact, w, Phi, kernelx, kernely, q, w_indices, zoptions, nzoptions, optiondiffsx, optiondiffsy)
}

